# Generated by Django 2.2.6 on 2020-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191231_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
